# Generated by Django 4.2.7 on 2023-11-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, verbose_name="player's  name")),
                ('position', models.CharField(choices=[('PG', 'Point guard'), ('SG', 'Shooting guard'), ('SF', 'Small forward'), ('PF', 'Power forward'), ('C', 'Center')], max_length=2)),
                ('games_played', models.IntegerField(default=0, verbose_name='games played')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftm', models.FloatField(default=0.0, verbose_name='free throw made')),
                ('fta', models.FloatField(default=0.0, verbose_name='free throw attempted')),
                ('two_pm', models.FloatField(default=0.0, verbose_name='two points made')),
                ('two_pa', models.FloatField(default=0.0, verbose_name='two points attempted')),
                ('three_pm', models.FloatField(default=0.0, verbose_name='three points made')),
                ('three_pa', models.FloatField(default=0.0, verbose_name='three points attempted')),
                ('reb', models.FloatField(default=0.0, verbose_name='rebounds')),
                ('blk', models.FloatField(default=0.0, verbose_name='blocks')),
                ('ast', models.FloatField(default=0.0, verbose_name='assists')),
                ('stl', models.FloatField(default=0.0, verbose_name='steals')),
                ('to', models.FloatField(default=0.0, verbose_name='turnovers')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='stats_api.player')),
            ],
            options={
                'verbose_name_plural': 'player stats',
            },
        ),
    ]
