# Generated by Django 4.2.7 on 2023-11-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20, verbose_name="player's  name")),
                ('position', models.CharField(choices=[('PG', 'Point guard'), ('SG', 'Shooting guard'), ('SF', 'Smallforward'), ('PF', 'Power forward'), ('C', 'Center')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('ft_attempts', models.FloatField(default=0.0)),
                ('ft_made', models.FloatField(default=0.0)),
                ('ft_percentage', models.FloatField(default=0.0)),
                ('two_pt_attempts', models.FloatField(default=0.0)),
                ('two_pt_made', models.FloatField(default=0.0)),
                ('two_pt_percentage', models.FloatField(default=0.0)),
                ('three_pt_attempts', models.FloatField(default=0.0)),
                ('three_pt_made', models.FloatField(default=0.0)),
                ('three_pt_percentage', models.FloatField(default=0.0)),
                ('points', models.FloatField(default=0.0)),
                ('rebounds', models.FloatField(default=0.0)),
                ('blocks', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('steals', models.FloatField(default=0.0)),
                ('turnovers', models.FloatField(default=0.0)),
                ('valorization', models.FloatField(default=0.0)),
                ('effective_field_goal_percentage', models.FloatField(default=0.0)),
                ('true_shooting_percentage', models.FloatField(default=0.0)),
                ('hollinger_assist_ratio', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_api.player')),
            ],
        ),
    ]
